# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout project sources   
      uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3https://github.com/CreepyOrb924/UnderWare/pulls
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
        
    - name: Run build with Gradle wrapper
      id: gradle
      run: ./gradlew build --scan
      
    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: build/libs
